export const PORTFOLIO_CONFIG = {
  name: "Prity Kumari",
  role: "AI/ML Enthusiast | Data Analyst | Problem Solver",
  bio: "Computer Science undergraduate passionate about Data Analytics and AI/ML, with good knowledge of Python, SQL, and problem-solving. Comfortable working with data, databases, and backend development concepts. Currently improving analytical and technical skills through projects and continuous learning.",
  githubUsername: "Rajkishor124",
  contactEmail: "pritykumari09748@gmail.com",
  phone: "+91-6202430103",
  location: "Ranchi, Jharkhand",
  socialLinks: {
    github: "https://github.com/Rajkishor124",
    linkedin: "https://linkedin.com",
    leetcode: "https://leetcode.com",
  },
  skills: [
    { name: "Python", category: "Languages", icon: "🐍" },
    { name: "Java", category: "Languages", icon: "☕" },
    { name: "C", category: "Languages", icon: "⚙️" },
    { name: "C++", category: "Languages", icon: "🔧" },
    { name: "HTML", category: "Frontend", icon: "🌐" },
    { name: "CSS", category: "Frontend", icon: "🎨" },
    { name: "MySQL", category: "Database", icon: "🗄️" },
    { name: "Git", category: "Tools", icon: "📦" },
    { name: "GitHub", category: "Tools", icon: "🐙" },
    { name: "IntelliJ IDEA", category: "Tools", icon: "💡" },
    { name: "VS Code", category: "Tools", icon: "📝" },
    { name: "Jupyter Notebook", category: "Tools", icon: "📓" },
    { name: "DSA", category: "Concepts", icon: "🧩" },
    { name: "Problem Solving", category: "Concepts", icon: "🧠" },
  ],
  education: [
    {
      year: "2023 – 2027",
      title: "B.Tech – Computer Science & Engineering",
      institution: "Cambridge Institute of Technology, Ranchi, India",
      description: "Pursuing Bachelor's degree with focus on Data Structures, Algorithms, AI/ML, and Software Engineering.",
    },
    {
      year: "2021 – 2023",
      title: "Senior Secondary (Class XII)",
      institution: "Ursuline Intermediate College, Ranchi, Jharkhand",
      description: "Completed with a strong foundation in science and mathematics.",
    },
  ],
  projects: [
    {
      title: "AI-Powered Sentiment Analyzer",
      description: "A machine learning application that analyzes sentiment from text data using Natural Language Processing. Built with Python, scikit-learn, and NLTK, it classifies user reviews and social media posts as positive, negative, or neutral with 89% accuracy.",
      tags: ["Python", "AI/ML", "NLP", "scikit-learn", "NLTK"],
      category: "AI/ML",
      link: "#",
      color: "var(--accent-primary)",
    },
    {
      title: "Automated Data Pipeline",
      description: "A robust Python-based ETL pipeline that extracts data from multiple sources (CSV, APIs, databases), transforms and cleans it using Pandas and NumPy, and loads it into a MySQL database with automated scheduling and error logging.",
      tags: ["Python", "Pandas", "NumPy", "MySQL", "ETL"],
      category: "Python",
      link: "#",
      color: "var(--accent-secondary)",
    },
    {
      title: "Student Performance Predictor",
      description: "A data analytics project that predicts student academic performance based on various factors like study hours, attendance, and socioeconomic background. Uses regression models and data visualization with Matplotlib and Seaborn.",
      tags: ["Python", "Data Analytics", "Matplotlib", "Seaborn"],
      category: "Python",
      link: "#",
      color: "var(--accent-tertiary)",
    },
  ],
  learning: [
    "Actively practicing Data Structures & Algorithms on LeetCode",
    "Exploring real-world project development using Python",
    "Building skills in Machine Learning and Data Analytics",
  ],
};
